name: fitness_nutrition_app
description: A Flutter app for fitness and nutrition

publish_to: 'none' # Remove this line if you plan to publish

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0" # Adjust the SDK version as necessary

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.8 # Ensure this is correctly indented
  firebase_auth: ^5.3.0
  http: ^0.13.4
  font_awesome_flutter: ^10.2.0  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/hand heart.png